### PR TITLE
added flag to exec to ignore non success return value (#46)

### LINKED ISSUE #46: Add flag to oc exec task to ignore non success return value
This might be useful when running a `oc create` where the resources already exist. There might be cases where one wants continue.

### PR DESCRIPTION
**Pull request by lstocchi**
it fixes #46 

With this PR if someone performs a command such as oc create or oc delete that fail because the resource has been already created/deleted, the task will not fail and the pipeline will not be blocked.

### CODE REVIEW

**Comment by jeffmaury** [comment]
Are you ignoring return code for every oc execution ? I think it's dangerous because we will blindly hide some errors (connection to the cluster,...).
I would rather add a flag ignoreAlreadyCreated to the create task and check the output

**Comment by lstocchi** [comment]
@jeffmaury As agreed previously I added a flag so the user can decide to ignore or not non-success return value. 

Commands like oc create/delete/patch/... have a chance to fail because the resource is already created/deleted/patched and the pipeline execution is stopped. Now the user can decide to skip these non-success return code and continue pipeline execution by setting this flag to true.

**Comment by lstocchi** [comment]
> LGTM. Just a single question: as we change the interface for the task, shouldn't we change the version of the task in the task descriptor ?

I would say that it's not mandatory but we could update it. It's up to us. To upload a new version of an extension in the marketplace we are forced to only change the version related to the extension. 

AFAIK the version in the task descriptor is used if you want to keep 2 versions of the same task so that when you upload the new version users can keep using the old one without any problem. But in this specific case there shouldn't be any problem bc the new input requested (task.getBoolInput('ignoreFlag');)  is not required so even if it's not set the task should work the same.

task.getBoolInput(name:string, required?:boolean) -> Gets the value of an input and converts to a bool. If required is true and the value is not set, it will throw.

**Comment by jeffmaury** [comment]
@lstocchi can you rebase it ?

**Comment by lstocchi** [comment]
> @lstocchi can you rebase it ?

Done :+1:

**Pull request merged**
