### PR TITLE
fix: added '.gz' case to unzipArchive method to avoid 'unknown archive format' error (#212)

### PR DESCRIPTION
**Pull request by schurlinga**
This PR fixes the issue #212

### CODE REVIEW

**Comment by lstocchi** [comment]
Thanks @schurlinga for this and sorry for the slow response.
In the switch i see there is support for `.tar.gz` so we lost it somewhere in some previous PR. 
I guess it would be better to use that extension. File with `.gz` extension are different from `.tar.gz` so using the `decompressTargz` for `.gz` doesn't seem too correct.
If you prefer i can handle it. Just let me know.
And sorry again for the trouble and slow response. Quite busy lately

**Comment by schurlinga** [comment]
Hi, thanks for your reply.
The downloaded file has the extension `.tar.gz`, but "path.extname(archive)" is, correctly, returning `.gz` when the compressed file ends with `.tar.gz`. So the switch case with `.tar.gz` will never be reached, but i think `decompressTargz` is the correct plugin in this case (and it works).

**Comment by lstocchi** [comment]
> Hi, thanks for your reply. The downloaded file has the extension `.tar.gz`, but "path.extname(archive)" is, correctly, returning `.gz` when the compressed file ends with `.tar.gz`. So the switch case with `.tar.gz` will never be reached, but i think `decompressTargz` is the correct plugin in this case (and it works).

Yes, it definitely works in your specific case. But let's say i try to upload a `.<another-extension-different-from-tar>.gz` file, the decompressTargz will probably fail.

**Comment by schurlinga** [comment]
Yes, you are right, so I guess the only solution would be to check if
archive ends with the string „.tar.gz“.

Luca Stocchi ***@***.***> schrieb am Di. 31. Jän. 2023 um
11:41:

**Comment by lstocchi** [comment]
> Yes, you are right, so I guess the only solution would be to check if archive ends with the string „.tar.gz“

i guess it would be better. I'll make a PR with a fix this afternoon.

**Comment by lstocchi** [comment]
@schurlinga closing this as i've created #215 . Thanks for your help!!

**Pull request closed without merging**
